### PR TITLE
irq_sources: Remove unneeded irq_sources.h

### PR DESCRIPTION
**Pull request by rugeGerritsen**
The interrupt numbers are already defined in the MDK files.

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

### CODE REVIEW

**Comment by aescolar** [comment]
Thanks @rugeGerritsen 
I guess this macros been renamed at some point in the MDK, is that the case? (and I'm guessing this was long ago?)
I'm guessing this is a backwards incompatible change, so if that is the case, it may be good mentioning in the commit since which is MDK and nrfx version it will work.

**Comment by rugeGerritsen** [comment]
> Thanks @rugeGerritsen I guess this macros been renamed at some point in the MDK, is that the case? (and I'm guessing this was long ago?) I'm guessing this is a backwards incompatible change, so if that is the case, it may be good mentioning in the commit since which is MDK and nrfx version it will work.

I went back to the oldest MDK I could find from 2012, and even there I couldn't find defines like `NRF5_IRQ_CCM_AAR_IRQn`. The oldest public releases available in github (https://github.com/NordicSemiconductor/nrfx/blob/v0.8.0/mdk/nrf52.h) doesn't have them either. So I believe it is unlikely that this will break existing applications

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
Let's then get the change merged in Zephyr, and merge this one after

**Comment by aescolar** [comment]
Merged

**Comment by aescolar** [comment]
Just FYI: I added a backwards compatibility note on the commit message

**Pull request closed without merging**
