### PR TITLE
nrfx HAL: Add nrf_clock_is_running

### PR DESCRIPTION
**Pull request by nordic-krch**
Added call that is now used by the clock control driver.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by nordic-krch** [comment]
@aescolar any chance to get that in?

**Comment by aescolar** [comment]
Hi @nordic-krch , I had missed this between all the other GitHub noise. Good that you pinged me

**Comment by aescolar** [comment]
For the record: Moved from https://github.com/zephyrproject-rtos/nrf_hw_models/pull/1

**Review by aescolar — DISMISSED** [review]
Hi @nordic-krch Seems the old PR comments still apply:

1) You are mostly copying pasting from the nrfx hal (which is what it should) but there is a few minor differences: how come?
2) Note that in between those differences you forgot the return type of the function (you need to add it)
3) You also need the static inline as the function body is in a header (otherwise you get one copy of the function per translation unit which you can't have, and it won't link together)

It would be nice also if you created another PR in the Zephyr main repo with the west manifest pointing to it so we can have a CI run of Zephyr with this module version (but first you can correct the 3 issues above)

**Comment by nordic-krch** [comment]
@aescolar sorry missed those comments there. Thanks, will apply.

**Comment by aescolar** [comment]
By the way @nordic-krch @anangl I fixed your permissions in this repo so you should be able to add reviewers and so forth. If that is not the case please tell.

**Comment by nordic-krch** [comment]
> You are mostly copying pasting from the nrfx hal (which is what it should) but there is a few minor differences: how come?

fixed that. I initially done it blindly without installing babblesim. Ended up installing it and compiling locally. It's being used by this PR: https://github.com/zephyrproject-rtos/zephyr/pull/24334 which now runs CI, will see how it goes.

**Comment by aescolar** [comment]
@nordic-krch There seems to be still quite a few differences compared to the real HAL?:
```diff
 {
     switch (domain)
     {
         case NRF_CLOCK_DOMAIN_LFCLK:
-            if (clk_src != NULL)
+            if (p_clk_src != NULL)
             {
-                (*(uint32_t *)clk_src) = ((p_reg->LFCLKSTAT & CLOCK_LFCLKSTAT_SRC_Msk)
-                                          >> CLOCK_LFCLKSTAT_SRC_Pos);
+                (*(nrf_clock_lfclk_t *)p_clk_src) =
+                    (nrf_clock_lfclk_t)((p_reg->LFCLKSTAT & CLOCK_LFCLKSTAT_SRC_Msk)
+                                        >> CLOCK_LFCLKSTAT_SRC_Pos);
             }
             if ((p_reg->LFCLKSTAT & CLOCK_LFCLKSTAT_STATE_Msk)
                 >> CLOCK_LFCLKSTAT_STATE_Pos)
@@ -329,10 +801,11 @@ static inline bool nrf_clock_is_running(NRF_CLOCK_Type const * p_reg,
             }
             break;
         case NRF_CLOCK_DOMAIN_HFCLK:
-            if (clk_src != NULL)
+            if (p_clk_src != NULL)
             {
-                (*(uint32_t *)clk_src) = ((p_reg->HFCLKSTAT & CLOCK_HFCLKSTAT_SRC_Msk)
-                                          >> CLOCK_HFCLKSTAT_SRC_Pos);
+                (*(nrf_clock_hfclk_t *)p_clk_src) =
+                    (nrf_clock_hfclk_t)((p_reg->HFCLKSTAT & CLOCK_HFCLKSTAT_SRC_Msk)
+                                        >> CLOCK_HFCLKSTAT_SRC_Pos);
             }
             if ((p_reg->HFCLKSTAT & CLOCK_HFCLKSTAT_STATE_Msk)
                 >> CLOCK_HFCLKSTAT_STATE_Pos)
@@ -342,10 +815,11 @@ static inline bool nrf_clock_is_running(NRF_CLOCK_Type const * p_reg,
             break;
 #if NRF_CLOCK_HAS_HFCLK192M
         case NRF_CLOCK_DOMAIN_HFCLK192M:
-            if (clk_src != NULL)
+            if (p_clk_src != NULL)
             {
-                (*(uint32_t *)clk_src) = ((p_reg->HFCLK192MSTAT & CLOCK_HFCLK192MSTAT_SRC_Msk)
-                                          >> CLOCK_HFCLK192MSTAT_SRC_Pos);
+                (*(nrf_clock_hfclk_t *)p_clk_src) =
+                    (nrf_clock_hfclk_t)((p_reg->HFCLK192MSTAT & CLOCK_HFCLK192MSTAT_SRC_Msk)
+                                        >> CLOCK_HFCLK192MSTAT_SRC_Pos);
             }
             if ((p_reg->HFCLK192MSTAT & CLOCK_HFCLK192MSTAT_STATE_Msk)
                 >> CLOCK_HFCLK192MSTAT_STATE_Pos)
@@ -360,13 +834,268 @@ static inline bool nrf_clock_is_running(NRF_CLOCK_Type const * p_reg,
                    CLOCK_HFCLKAUDIOSTAT_STATE_Msk;
 #endif
         default:
+            NRFX_ASSERT(0);
             return false;
     }
     return false;
 }
```

**Comment by nordic-krch** [comment]
@aescolar what are you comparing? seems like latest nrfx. I took nrfx version from zephyr and just removed NRFX_ASSERT(). Was not sure if it's present in bsim.

**Comment by aescolar** [comment]
I compared with "nrfx 2.2.0" a5397bea558fb4b6838081a22d1ee679289d7417 the latest in your HAL repo

**Comment by aescolar** [comment]
@nordic-krch But yep, I can see the version in Zephyr is almost the same that you are merging in. If @anangl is ok with merging an older version here instead of the latest I'm ok with that.
But about the NRFX_ASSERT() it'd be nicer to add the definition if it is missing so it is there for the future. You can start a nrfx_glue.h with just that or add an empty definition into nrf_soc_if.h

**Comment by nordic-krch** [comment]
> add an empty definition into nrf_soc_if.h

done

@anangl let me know if you have any preference regarding nrfx version i should take `nrf_clock_is_running` from. Zephyr one (current status) or latest.

**Review by aescolar — COMMENTED** [review]
"Approved" subject to @anangl blessing

**Comment by anangl** [comment]
> @anangl let me know if you have any preference regarding nrfx version i should take `nrf_clock_is_running` from. Zephyr one (current status) or latest.

@nordic-krch I think it would be better to use the function from commit a5397bea558fb4b6838081a22d1ee679289d7417, which will be soon (before the feature freeze for Zephyr 2.3) merged to master. This will save us one update of ext_NRF52_hw_models. The changes from `(*(uint32_t *)clk_src) = ...` to `(*(nrf_clock_lfclk_t *)p_clk_src) = ...` and so on in this function that are brought by nrfx 2.2 are quite important corrections.

**Comment by nordic-krch** [comment]
@anangl done.

**Review by anangl — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
By the way, @nordic-krch I would have asked you to update the west manifest in the Zephyr PR to provisionally point to this PR to try it in CI, but I have tried it quickly locally. (so no need to do anything now, but just so that you know that would have been normal procedure)

**Review by wopu-ot — APPROVED** [review]

**Comment by nordic-krch** [comment]
> I would have asked you to update the west manifest in the Zephyr PR 

it's done here: https://github.com/zephyrproject-rtos/zephyr/pull/24334/files#diff-4ae7a6d2c692e706a33f7a71d3eb25d2

What are the next steps? How to update https://github.com/zephyrproject-rtos/nrf_hw_models ?

**Comment by aescolar** [comment]
>What are the next steps? How to update https://github.com/zephyrproject-rtos/nrf_hw_models ?

It goes automatically (just a couple of minutes delay)

**Pull request merged**
